; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .  
include_dir = . 

[env:seeed_xiao_esp32c3]
;platform = espressif32
platform = espressif32@^6.0.0  ; Arduinoコア v2.x系を使用するように固定
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_upload.flash_size = 4MB
board_build.flash_size = 4MB

lib_deps =
    olikraus/U8g2@^2.35.0
    https://github.com/hjd1964/ephemeris
    h2zero/NimBLE-Arduino@^1.4.0
    
lib_compat_mode = strict